---
#ansy playbook start with three dash
-
###this minus in yaml indicate a list of items. the play contains a list of play
  hosts: ansiblenode,client1
  vars:
    motd_redhat: "welcome to redhat linux\n"
    motd_ubuntu: "welcome to ubuntu linux \n"
  
  tasks:
    - name: install java
      package: 
      #this module autmatically identify the os and run the installation command accoring to your os
        name: java-11-openjdk-headless
        state: latest
    - name: Download file from a file path
      get_url:
       url: https://www-us.apache.org/dist/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz
       dest: cd /opt/
    - name: Unarchive a file that is already on the remote machine
      unarchive:
       src: /opt/apache-maven-3.8.5-bin.tar.gz
       dest: /opt
       remote_src: yes